# Generated by Django 6.0 on 2025-12-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_skillexchange_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(),
        ),
    ]
