# Generated by Django 6.0 on 2025-12-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_testimonial_approved_userprofile_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('language', 'Language'), ('business', 'Business'), ('music', 'Music'), ('art', 'Art'), ('sports', 'Sports'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
